version: '3'
services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    volumes:
      - .:/app
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
  db:
    image: postgres
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env