version: '3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - local-var.env
    volumes:
      - .:/app
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres

  deploy_staging:
    build: .
    env_file:
      - deploy-staging-var.env

  deploy_production:
    build: .
    env_file:
      - deploy-production-var.env