# Generated by Django 3.0.6 on 2020-11-25 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuffuser',
            options={'ordering': ['stuff_name', 'designation_group', 'designation', 'mobile_number_primary', 'image']},
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event/'),
        ),
    ]
