# Generated by Django 3.0.6 on 2020-11-23 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='opt',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
