# Generated by Django 3.0.6 on 2020-11-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuffuser',
            options={'ordering': ['stuff_name', 'designation_group', 'designation', 'mobile_number_primary']},
        ),
        migrations.AlterField(
            model_name='stuffuser',
            name='mobile_number_secondary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
