# Generated by Django 3.0.6 on 2020-11-21 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_messageuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'end_date', 'name', 'slug', 'created']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='updated_at',
            new_name='updated',
        ),
    ]
