# Generated by Django 3.0.6 on 2020-11-25 05:19

import api.models
import django.core.files.storage
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201125_0359'),
        
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/club_facility/', location='/home/vikram/wsit_sarwar/gulshan_club_api/media/club_facility/'), upload_to='', verbose_name=api.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='clubfacilitydetail',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/club_facility_detail/', location='/home/vikram/wsit_sarwar/gulshan_club_api/media/club_facility_detail/'), upload_to='', verbose_name=api.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/event/', location='/home/vikram/wsit_sarwar/gulshan_club_api/media/event/'), upload_to='', verbose_name=api.models.image_directory_path),
        ),
        migrations.AlterField(
            model_name='stuffuser',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/stuff_user/', location='/home/vikram/wsit_sarwar/gulshan_club_api/media/stuff_user/'), upload_to='', verbose_name=api.models.image_directory_path),
        ),
    ]
