# Generated by Django 3.0.6 on 2021-01-13 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.CharField(blank=True, choices=[('doard_director', 'Board Of Director'), ('active', 'Active'), ('inactive', 'Inactive')], default='Active', max_length=50, null=True),
        ),
    ]
