# Generated by Django 3.0.6 on 2020-11-25 05:56

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201125_0519'),
        
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='stuff_user/'),
        ),
        migrations.AlterField(
            model_name='clubfacility',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility/'),
        ),
        migrations.AlterField(
            model_name='clubfacilitydetail',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility_deatil/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='event/'),
        ),
        migrations.AlterField(
            model_name='stuffuser',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='stuff_user/'),
        ),
    ]
