# Generated by Django 3.0.6 on 2020-11-25 06:30

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201125_0556'),
        
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuffuser',
            options={'ordering': ['stuff_name', 'designation_group', 'designation', 'mobile_number_primary', 'image_medium']},
        ),
        migrations.RenameField(
            model_name='stuffuser',
            old_name='image',
            new_name='image_medium',
        ),
        migrations.AddField(
            model_name='stuffuser',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='stuff_user/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='member_user/'),
        ),
    ]
