# Generated by Django 3.0.6 on 2021-06-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210425_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=250)),
                ('trxID', models.CharField(blank=True, max_length=250)),
                ('ammount', models.CharField(blank=True, max_length=250)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('merchant_invoice', models.CharField(blank=True, max_length=250)),
                ('transaction_status', models.CharField(blank=True, max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('payment_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_by', to=settings.AUTH_USER_MODEL)),
                ('payment_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['payment_by', 'payment_to'],
            },
        ),
    ]
