# Generated by Django 3.0.6 on 2020-11-21 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201121_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticeboard',
            name='tag',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
