# Generated by Django 3.0.6 on 2020-11-25 07:00

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201125_0630'),
        
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clubfacility',
            options={'ordering': ['name', 'description']},
        ),
        migrations.AlterModelOptions(
            name='clubfacilitydetail',
            options={'ordering': ['name', 'description', 'image_medium', 'image_thumbnail']},
        ),
        migrations.AlterModelOptions(
            name='stuffuser',
            options={'ordering': ['stuff_name', 'designation_group', 'designation', 'mobile_number_primary']},
        ),
        migrations.RemoveField(
            model_name='clubfacility',
            name='image',
        ),
        migrations.RemoveField(
            model_name='clubfacilitydetail',
            name='image',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='clubfacility',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility/medium/'),
        ),
        migrations.AddField(
            model_name='clubfacility',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility/thumbnail/'),
        ),
        migrations.AddField(
            model_name='clubfacilitydetail',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility_detail/medium/'),
        ),
        migrations.AddField(
            model_name='clubfacilitydetail',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='club_facility_detail/thumbnail/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='member_user/medium/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='member_user/thumbnail/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='event/medium/'),
        ),
        migrations.AddField(
            model_name='event',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='event/thumbnail/'),
        ),
        migrations.AlterField(
            model_name='stuffuser',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='stuff_user/medium/'),
        ),
        migrations.AlterField(
            model_name='stuffuser',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='stuff_user/thumbnail/'),
        ),
    ]
