# Generated by Django 3.0.6 on 2021-06-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_postpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpayment',
            old_name='trxID',
            new_name='trx_id',
        ),
    ]
