# Generated by Django 3.0.6 on 2020-11-25 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20201125_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_primary',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
