# Generated by Django 3.0.6 on 2021-06-22 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210622_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postpayment',
            old_name='ammount',
            new_name='amount',
        ),
    ]
