# Generated by Django 3.0.6 on 2020-11-21 18:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20201121_1835'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDeatail',
            new_name='UserDetail',
        ),
    ]
