# Generated by Django 3.0.6 on 2021-06-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210622_1158'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postpayment',
            table='post_payment',
        ),
    ]
