# Generated by Django 3.0.6 on 2021-06-22 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20210622_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpayment',
            name='payment_type',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
