# Generated by Django 3.0.6 on 2020-11-25 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20201125_0958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='marital_status',
            new_name='marital_status',
        ),
    ]
