# Generated by Django 3.0.6 on 2021-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_postpayment_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpayment',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postpayment',
            name='updated_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
