# Generated by Django 3.0.6 on 2021-07-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210711_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='postpayment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
