# Generated by Django 3.0.6 on 2021-07-19 02:44

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticeboard',
            name='image_medium',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='notice/medium/'),
        ),
        migrations.AddField(
            model_name='noticeboard',
            name='image_thumbnail',
            field=stdimage.models.StdImageField(blank=True, null=True, upload_to='notice/thumbnail/'),
        ),
    ]
