# Generated by Django 3.0.6 on 2021-07-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20210719_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfacility',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='clubfacilitydetail',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
