# Generated by Django 3.0.6 on 2021-07-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210719_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfacilitydetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
