# Generated by Django 3.0.6 on 2021-07-19 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210719_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubfacility',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
