# Generated by Django 3.0.6 on 2021-07-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210719_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
