# Generated by Django 3.0.6 on 2021-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210727_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='persion',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
