# Generated by Django 3.0.6 on 2021-07-29 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210730_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
