# Generated by Django 3.0.6 on 2021-07-29 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20210730_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='test',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
