# Generated by Django 3.0.6 on 2021-07-29 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20210730_0304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='test',
        ),
    ]
