# Generated by Django 3.0.6 on 2021-07-29 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20210730_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_datetime',
            field=models.DateTimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='reservation_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
