# Generated by Django 3.0.6 on 2021-07-29 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_auto_20210730_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='reservation_datetime',
            new_name='reservation_date',
        ),
    ]
